SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1060
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

BRICK_WIDTH = SCREEN_WIDTH // 8 - 4
BRICK_HEIGHT = 101
BRICK_SIZE = (BRICK_WIDTH, BRICK_HEIGHT)

BALL_RADIUS = 23
BALL_SIZE = (BALL_RADIUS * 2,) * 2

PLAYER_WIDTH = 320
PLAYER_HEIGHT = 40
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)

FPS = 60
